Repository tryber/sd-04-trybeer, pull requests merged in 2020-11, with the labels that each got.

#6 req-0 basic structure
  front-end/src/App.js
  front-end/src/pages/Login.jsx
  front-end/src/routes.js
Labels: GROUP-05

#20 Group 1 req 1 front
  back-end/controllers/loginController.js
  back-end/index.js
  back-end/middleware/index.js
  back-end/middleware/userAuth.js
  back-end/middleware/validations.js
  back-end/models/connection.js
  back-end/models/loginModel.js
  back-end/package-lock.json
  back-end/package.json
  back-end/services/createToken.js
  back-end/services/loginService.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.css
  front-end/src/App.js
  front-end/src/components/header.js
  front-end/src/index.js
  front-end/src/logo.svg
  front-end/src/pages/Login.jsx
  front-end/src/pages/index.js
  front-end/src/serviceWorker.js
  front-end/src/services/TrybeerApi.js
  front-end/src/services/validate.js
  package-lock.json
Labels: Group-1

#33 Req 4 tela de perfil
  back-end/controllers/userController.js
  back-end/routes.js
  front-end/public/index.html
  front-end/src/App.js
  front-end/src/context/AppContext.jsx
  front-end/src/pages/Profile.jsx
  front-end/src/routes.js
Labels: GROUP-05

#39 refact login service front
  front-end/src/pages/Login.jsx
  front-end/src/services/api.js
Labels: GROUP-05

#45 Group 1 req 1 front Css done
  front-end/src/css/loginPage.css
  front-end/src/fonts/Simpsonfont.ttf
  front-end/src/fonts/akbar.ttf
  front-end/src/images/404.png
  front-end/src/images/DuffLogo.png
  front-end/src/images/DuffLogoTransparent.png
  front-end/src/images/barney.png
  front-end/src/images/beerLiquid.png
  front-end/src/images/beerMug.png
  front-end/src/images/getDuffed.png
  front-end/src/images/homer-simpson-happy.png
  front-end/src/images/index.js
  front-end/src/images/loading.gif
  front-end/src/images/logout.png
  front-end/src/pages/Login.jsx
  package.json
Labels: Group-1

#2 Leonardo-main-group-2
  back-end/auth/createToken.js
  back-end/config/config.js
  back-end/controllers/userController.js
  back-end/index.js
  back-end/middlewares/userMiddlewares.js
  back-end/model/connection.js
  back-end/model/userModel.js
  back-end/routers/userRouters.js
  cypress/plugins/index.js
  front-end/package-lock.json
  front-end/package.json
  front-end/public/index.html
  front-end/src/App.js
  front-end/src/Components/buttonEnviar.js
  front-end/src/Pages/adminPage.js
  front-end/src/Pages/clientPage.js
  front-end/src/Pages/login.js
  front-end/src/Pages/registro.js
  front-end/src/index.js
  front-end/src/serviceWorker.js
  front-end/src/services/userApi.js
  package-lock.json
  package.json
Labels: GRUPO-2, need approve

#54 Group 1 - Requisito 2 e Requisito 4
  back-end/.eslintrc.json
  back-end/controllers/userController.js
  back-end/index.js
  back-end/middleware/validations.js
  back-end/models/genericModel.js
  back-end/models/loginModel.js
  back-end/models/userModel.js
  back-end/services/loginService.js
  back-end/services/userService.js
  front-end/src/App.js
  front-end/src/pages/Register.jsx
  front-end/src/pages/UserProfile.jsx
  front-end/src/pages/index.js
  front-end/src/services/TrybeerApi.js
  front-end/src/services/validate.js
Labels: Group-1

#60 Req2 e Req4
  back-end/controllers/userController.js
  back-end/index.js
  back-end/models/userModel.js
  back-end/services/userService.js
  front-end/src/pages/Register.jsx
  front-end/src/pages/UserProfile.jsx
  front-end/src/services/TrybeerApi.js
Labels: Group-1

#49 Componente de detalhes do pedido criado
  front-end/src/components/ProductDetailsCard/index.js
  front-end/src/components/ProductDetailsCard/styles.css
  front-end/src/pages/MyOrdereds/index.js
  front-end/src/pages/ProductDetails/index.js
  front-end/src/pages/ProductDetails/styles.css
  front-end/src/routes.js
Labels: code-review

#62 G5 req02 register page
  back-end/controllers/userController.js
  back-end/middlewares/checkEmailInDatabase.js
  back-end/models/userModel.js
  back-end/routes.js
  back-end/services/userService.js
  front-end/src/pages/Register.jsx
  front-end/src/routes.js
  front-end/src/utils/inputValidations.js
Labels: GROUP-05

#26 Registro (front-end)
  back-end/controllers/userController.js
  back-end/index.js
  back-end/models/userModel.js
  front-end/src/context/index.js
  front-end/src/imgs/beer.svg
  front-end/src/imgs/logo.png
  front-end/src/imgs/trybeer & cia..png
  front-end/src/pages/Register/index.js
  front-end/src/pages/Register/styles.css
  front-end/src/routes.js
Labels: code-review

#72 G5 req 4 profile working
  back-end/controllers/userController.js
  back-end/models/userModel.js
  back-end/routes.js
  back-end/services/userService.js
  front-end/src/pages/Profile.jsx
  front-end/src/routes.js
Labels: GROUP-05

#53 group-2 - register user
  back-end/controllers/userController.js
  back-end/index.js
  back-end/model/connection.js
  back-end/model/userModel.js
  front-end/src/App.js
  front-end/src/Pages/registro.js
  front-end/src/services/userApi.js
Labels: GRUPO-2

#73 G5 req5 products backend
  back-end/controllers/productController.js
  back-end/index.js
  back-end/models/productModel.js
  back-end/public/images/Antarctica Pilsen 300ml.jpg
  back-end/public/images/Becks 330ml.jpg
  back-end/public/images/Becks 600ml.jpg
  back-end/public/images/Brahma 600ml.jpg
  back-end/public/images/Brahma Duplo Malte 350ml.jpg
  back-end/public/images/Heineken 600ml.jpg
  back-end/public/images/Skol 269ml.jpg
  back-end/public/images/Skol Beats Senses 269ml.jpg
  back-end/public/images/Skol Beats Senses 313ml.jpg
  back-end/public/images/Skol Lata 350ml.jpg
  back-end/public/images/Stella Artois 275ml.jpg
  back-end/routes.js
  back-end/services/productService.js
Labels: GROUP-05

#83 G5 req05 products component
  front-end/src/components/ProductCard.css
  front-end/src/components/ProductCard.jsx
  front-end/src/components/images/Antarctica Pilsen 300ml.jpg
  front-end/src/components/images/Becks 330ml.jpg
  front-end/src/components/images/Becks600ml.jpg
  front-end/src/components/images/Brahma 600ml.jpg
  front-end/src/components/images/Brahma Duplo Malte 350ml.jpg
  front-end/src/components/images/Heineken 600ml.jpg
  front-end/src/components/images/Skol 269ml.jpg
  front-end/src/components/images/Skol Beats Senses 269ml.jpg
  front-end/src/components/images/Skol Beats Senses 313ml.jpg
  front-end/src/components/images/Skol Lata 350ml.jpg
  front-end/src/components/images/Stella Artois 275ml.jpg
  front-end/src/context/AppContext.jsx
  front-end/src/pages/Products.jsx
Labels: GROUP-05

#87 Resolve topbar lost
  .github/workflows/main.yml
  back-end/models/productModel.js
  front-end/src/pages/Products.jsx
Labels: GROUP-05

#91 G5 req 09
  front-end/src/components/ClientBar.css
  front-end/src/components/ClientBar.jsx
  front-end/src/pages/admin/Orders.jsx
  front-end/src/pages/admin/Profile.jsx
  front-end/src/pages/test.jsx
  front-end/src/routes.js
Labels: GROUP-05

#94 G5 req 05 - list products + css
  front-end/src/App.css
  front-end/src/components/ProductCard.css
  front-end/src/components/ProductCard.jsx
  front-end/src/pages/Products.jsx
Labels: GROUP-05

#96 Rangel conserta o guarda roupa
  back-end/package-lock.json
  front-end/package-lock.json
  front-end/src/components/Header/index.js
  front-end/src/components/Login/index.js
  front-end/src/components/OderedsCard/index.js
  front-end/src/components/ProductDetailsCard/index.js
  front-end/src/components/ProductsCard/index.js
  front-end/src/components/Rodape/index.js
  front-end/src/components/SideMenu/index.js
  front-end/src/components/SideMenuAdmin/index.js
  front-end/src/components/TopMenu/TopHamburgerToggle/TopHamburgerToggle.js
  front-end/src/components/TopMenu/index.js
  front-end/src/pages/ClientProfile/index.js
  front-end/src/pages/LoginPage/index.js
  front-end/src/pages/MyOrdereds/index.js
  front-end/src/pages/ProductDetails/index.js
  front-end/src/pages/Products/index.js
  front-end/src/pages/Register/index.js
  front-end/src/routes.js
  front-end/src/services/api.js
  package-lock.json
Labels: code-review

#102 Leonardo main group 2
  back-end/controllers/productController.js
  back-end/images/Antarctica Pilsen 300ml.jpg
  back-end/images/Becks 330ml.jpg
  back-end/images/Becks 600ml.jpg
  back-end/images/Brahma 600ml.jpg
  back-end/images/Brahma Duplo Malte 350ml.jpg
  back-end/images/Heineken 600ml.jpg
  back-end/images/Skol 269ml.jpg
  back-end/images/Skol Beats Senses 269ml.jpg
  back-end/images/Skol Beats Senses 313ml.jpg
  back-end/images/Skol Lata 350ml.jpg
  back-end/images/Stella Artois 275ml.jpg
  back-end/index.js
  back-end/model/productModel.js
  back-end/routers/productRouters.js
  front-end/public/index.html
  front-end/src/App.js
  front-end/src/Components/buttonEnviar.js
  front-end/src/Components/shopcart.js
  front-end/src/Pages/clientPage.js
  front-end/src/context/appBeerContext.js
  front-end/src/context/provider.js
  front-end/src/services/productApi.js
Labels: GRUPO-2

#125 Rangel conserta o guarda roupa2
  back-end/controllers/userController.js
  back-end/index.js
  back-end/models/userModel.js
  back-end/routes/index.js
  back-end/routes/userRoutes.js
  back-end/services/userService.js
  front-end/src/components/Header/index.js
  front-end/src/components/Login/index.js
  front-end/src/components/SideMenu/index.js
  front-end/src/pages/Register/index.js
  front-end/src/validation/index.js
Labels: code-review

#126 Requisito 8
  back-end/controllers/saleController.js
  back-end/index.js
  back-end/models/connection.js
  back-end/models/saleModel.js
  back-end/services/saleService.js
  front-end/src/App.js
  front-end/src/components/OrderDetails/SalesDetails.jsx
  front-end/src/pages/Checkout.jsx
  front-end/src/pages/OrderDetail.jsx
  front-end/src/redux/actions.js
  front-end/src/redux/reducers/cartReducer.js
  front-end/src/services/TrybeerApi.js
Labels: Group-1

#128 products page css done
  front-end/.eslintrc.json
  front-end/src/components/ListProducts/CardProduct.jsx
  front-end/src/components/ListProducts/index.jsx
  front-end/src/components/Loading.jsx
  front-end/src/components/forms/LoginForm.jsx
  front-end/src/css/formPage.css
  front-end/src/css/header.css
  front-end/src/css/listProducts.css
  front-end/src/css/loading.css
  front-end/src/css/profile.css
  front-end/src/images/happy.png
  front-end/src/images/index.js
  front-end/src/index.css
  front-end/src/pages/Products.jsx
Labels: Group-1

#141 Requisito 10 passando
  front-end/src/components/ClientBar.css
  front-end/src/pages/admin/CSS/Profile.css
  front-end/src/pages/admin/Profile.jsx
Labels: GROUP-05

#144 Rangel conserta o guarda roupa4
  back-end/controllers/userController.js
  back-end/models/userModel.js
  back-end/routes/userRoutes.js
  back-end/services/userService.js
  front-end/src/components/Header/style.css
  front-end/src/components/Login/index.js
  front-end/src/components/Login/style.css
Labels: code-review

#147 G5 req6 checkout backend
  back-end/controllers/checkoutController.js
  back-end/controllers/saleController.js
  back-end/middlewares/findUserIdByEmail.js
  back-end/models/saleModel.js
  back-end/models/salesProductsModel.js
  back-end/routes.js
  back-end/services/saleService.js
  back-end/services/salesProductsService.js
Labels: GROUP-05

#129 group 2 - requisito 6 - Checkout
  back-end/controllers/orderController.js
  back-end/index.js
  back-end/model/orderModel.js
  back-end/routers/salesRouters.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.js
  front-end/src/Pages/checkoutPage.js
  front-end/src/services/orderApi.js
Labels: GRUPO-02

#149 G5 Req 08 Order Details
  back-end/controllers/saleController.js
  back-end/models/saleModel.js
  back-end/models/simpleConnection.js
  back-end/routes.js
  back-end/services/saleService.js
  front-end/src/pages/Details.css
  front-end/src/pages/Details.jsx
  front-end/src/routes.js
Labels: GROUP-05

#153 G5 req 6 starting checkout screen
  back-end/routes.js
  front-end/src/context/AppContext.jsx
  front-end/src/pages/CloseOrder.css
  front-end/src/pages/CloseOrder.jsx
  front-end/src/pages/Orders.jsx
  front-end/src/pages/Products.jsx
Labels: GROUP-05

#159 Rangel conserta o guarda roupa5
  front-end/src/components/Header/components/NavBar/index.js
  front-end/src/components/Header/components/NavBar/styles.css
  front-end/src/components/Login/index.js
  front-end/src/pages/Products/index.js
Labels: code-review

#157 resolvendo bugs da api
  back-end/controllers/checkoutController.js
  back-end/middlewares/findUserIdByEmail.js
  back-end/models/saleModel.js
Labels: GROUP-05

#163 Rangel conserta o guarda roupa6
  back-end/controllers/userController.js
  back-end/models/userModel.js
  back-end/routes/userRoutes.js
  back-end/services/userService.js
  front-end/src/components/Header/index.js
  front-end/src/components/Login/index.js
  front-end/src/pages/ClientProfile/index.js
  front-end/src/pages/ClientProfile/styles.css
  front-end/src/pages/LoginPage/index.js
  front-end/src/pages/Register/index.js
  front-end/src/validation/index.js
Labels: code-review

#165 Rangel conserta o guarda roupa8
  back-end/controllers/index.js
  back-end/controllers/productsController.js
  back-end/controllers/userController.js
  back-end/images/Antarctica Pilsen 300ml.jpg
  back-end/images/Becks 330ml.jpg
  back-end/images/Becks 600ml.jpg
  back-end/images/Brahma 600ml.jpg
  back-end/images/Brahma Duplo Malte 350ml.jpg
  back-end/images/Heineken 600ml.jpg
  back-end/images/Skol 269ml.jpg
  back-end/images/Skol Beats Senses 269ml.jpg
  back-end/images/Skol Beats Senses 313ml.jpg
  back-end/images/Skol Lata 350ml.jpg
  back-end/images/Stella Artois 275ml.jpg
  back-end/index.js
  back-end/models/index.js
  back-end/models/productsModel.js
  back-end/models/userModel.js
  back-end/routes/index.js
  back-end/routes/productsRoutes.js
  back-end/routes/userRoutes.js
  back-end/services/index.js
  back-end/services/productsService.js
  front-end/src/PrivateRoute.js
  front-end/src/auth.js
  front-end/src/components/Login/index.js
  front-end/src/components/OderedsCard/index.js
  front-end/src/components/ProductsCard/index.js
  front-end/src/components/ProductsCard/styles.css
  front-end/src/components/Rodape/index.js
  front-end/src/components/Rodape/styles.css
  front-end/src/components/SideMenuAdmin/styles.css
  front-end/src/context/index.js
  front-end/src/pages/LoginPage/index.js
  front-end/src/pages/MyOrdereds/index.js
  front-end/src/pages/MyOrdereds/styles.css
  front-end/src/pages/Products/index.js
  front-end/src/pages/Products/styles.css
  front-end/src/pages/Register/index.js
  front-end/src/routes.js
  front-end/src/validation/index.js
Labels: code-review

#168 Req 11
  back-end/controllers/checkoutController.js
  back-end/controllers/getDataTestController.js
  back-end/controllers/userController.js
  back-end/routes.js
  front-end/src/components/CardAdmOrders.css
  front-end/src/components/CardAdmOrders.jsx
  front-end/src/components/ClientBar.css
  front-end/src/components/ClientBar.jsx
  front-end/src/components/ProductCard.jsx
  front-end/src/pages/CloseOrder.jsx
  front-end/src/pages/Login.jsx
  front-end/src/pages/admin/CSS/Orders.css
  front-end/src/pages/admin/Orders.jsx
  front-end/src/pages/admin/Profile.jsx
Labels: GROUP-05

#172 Mudanças no css
  front-end/src/assets/logo-sem-fundo.svg
  front-end/src/assets/user.svg
  front-end/src/assets/woman-register.svg
  front-end/src/components/Header/components/NavBar/index.js
  front-end/src/components/Header/components/NavBar/styles.css
  front-end/src/components/Header/index.js
  front-end/src/components/Header/style.css
  front-end/src/components/Login/index.js
  front-end/src/components/Login/style.css
  front-end/src/components/ProductsCard/index.js
  front-end/src/components/ProductsCard/styles.css
  front-end/src/components/Rodape/styles.css
  front-end/src/components/TopMenu/styles.css
  front-end/src/pages/ClientProfile/index.js
  front-end/src/pages/ClientProfile/styles.css
  front-end/src/pages/Products/styles.css
  front-end/src/pages/Register/index.js
  front-end/src/pages/Register/styles.css
Labels: code-review

#174 G5 test api
  back-end/controllers/checkoutController.js
  back-end/controllers/saleController.js
  back-end/models/saleModel.js
  back-end/models/salesProductsModel.js
  back-end/routes.js
  back-end/services/saleService.js
  front-end/src/components/MyOrdersCard.css
  front-end/src/components/MyOrdersCard.jsx
  front-end/src/pages/CloseOrder.jsx
  front-end/src/pages/Details.jsx
  front-end/src/pages/Orders.jsx
  front-end/src/routes.js
Labels: GROUP-05

#180 G5 Req 08 cc issues
  back-end/controllers/checkoutController.js
Labels: GROUP-05

#186 Rangel conserta o guarda roupa9
  back-end/controllers/productsController.js
  back-end/models/productsModel.js
  back-end/routes/productsRoutes.js
  back-end/services/productsService.js
  front-end/src/components/OderedsCard/index.js
  front-end/src/components/ProductsCard/index.js
  front-end/src/pages/MyOrdereds/index.js
  front-end/src/pages/MyOrdersADM/index.js
Labels: code-review

#189 Rangel conserta o guarda roupa10
  front-end/src/components/Checkout/components/AdressForm/index.js
  front-end/src/components/Checkout/components/Products/index.js
  front-end/src/components/Checkout/index.js
  front-end/src/components/Header/index.js
  front-end/src/components/OderedsCard/index.js
  front-end/src/components/Rodape/index.js
  front-end/src/components/Rodape/styles.css
  front-end/src/context/index.js
  front-end/src/pages/CheckoutPage/index.js
  front-end/src/pages/ProductDetails/index.js
  front-end/src/pages/ProductDetails/styles.css
  front-end/src/routes.js
  front-end/src/validation/index.js
Labels: code-review

#201 Nao sei, agora passa
  back-end/models/productsModel.js
  front-end/src/components/Checkout/components/AdressForm/index.js
  front-end/src/components/Header/components/NavBar/styles.css
  front-end/src/components/SideMenuAdmin/index.js
Labels: code-review

#202 Luma conserta uma comodazinha
  back-end/controllers/productsController.js
  back-end/models/getSession.js
  back-end/models/productsModel.js
  back-end/routes/productsRoutes.js
  back-end/services/productsService.js
  front-end/src/components/ProductDetailsCard/index.js
  front-end/src/pages/ProductDetails/index.js
  front-end/src/validation/index.js
Labels: code-review
